#!/bin/python3

import math
import os
import random
import re
import sys


def dec2bin(n):
    new_list = []
    while(n):
        new_list.append(n%2)
        n = n//2
    new_list.reverse()
    return new_list

if __name__ == '__main__':
    n = int(input())
    
    result = dec2bin(n)
    count = 0
    max_score = 1
    for i in result:
        if i==1:
            count+=1
        else:
            if(count>0):
                max_score = max(max_score,count)
            count = 0
    if (count>0):
        max_score = max(max_score,count)
    print(max_score)
                
